[package]
name = "loon-macos"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
loon-types = { path = "../loon-types" }
loon-ops = { path = "../loon-ops" }
loon-client = { path = "../loon-client" }

[dev-dependencies]
loon-objectstore = { path = "../loon-objectstore" }
loon-testkit = { path = "../loon-testkit" }
serde_yaml.workspace = true
