[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "Build automation for the LoonDB workspace"

[dependencies]
anyhow.workspace = true
loon-client = { path = "../crates/loon-client" }
loon-ops = { path = "../crates/loon-ops" }
loon-server = { path = "../crates/loon-server" }
loon-testkit = { path = "../crates/loon-testkit" }
loon-types = { path = "../crates/loon-types" }
serde_json.workspace = true
