//! Per-operation options shared by the embedded runtime and HTTP client.

use crate::{
    ActorRef, AttributeKey, AttributeRevisionNo, AttributeValue, CheckpointId, CommitId,
    DeleteDirectoryBehavior, DestinationBehavior, InodeId, RevisionNo,
};
use std::collections::BTreeMap;

/// Commit settings shared by every filesystem mutation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CommitOptions {
    /// Actor responsible for the commit, as supplied by the application.
    pub actor: ActorRef,
    /// The optional idempotency key, generated by LoonFS when absent.
    pub commit_id: Option<CommitId>,
    /// The optional commit message that forms part of the commit identity.
    pub message: Option<String>,
}

impl CommitOptions {
    /// Creates settings with no commit ID or message.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            actor,
            commit_id: None,
            message: None,
        }
    }
}

/// Options for stating one path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StatPathOptions {
    /// Whether to include the inode's attribute map and revision, enabled by default.
    pub include_attributes: bool,
    /// The snapshot for the path read; inode lookups do not support snapshots.
    pub snapshot_id: Option<CheckpointId>,
}

impl Default for StatPathOptions {
    fn default() -> Self {
        Self {
            include_attributes: true,
            snapshot_id: None,
        }
    }
}

/// Options for listing a directory.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ListPathEntriesOptions {
    /// Whether to include each entry's attribute map and revision, disabled by default.
    pub include_attributes: bool,
    /// Read the directory from this snapshot.
    pub snapshot_id: Option<CheckpointId>,
}

/// Options for listing a directory's children by parent inode.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ListInodeChildrenOptions {
    /// Whether to include each entry's attribute map and revision, disabled by default.
    pub include_attributes: bool,
}

/// Options for writing and removing an inode's attributes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UpdateAttributesOptions {
    /// The attributes to write, replacing values for matching keys and leaving other
    /// keys unchanged.
    pub set: BTreeMap<AttributeKey, AttributeValue>,
    /// Keys to remove.
    pub remove: Vec<AttributeKey>,
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
    /// The inode that the path must still resolve to before the update.
    pub expected_inode_id: Option<InodeId>,
    /// The attribute revision that must still be current before the update.
    pub expected_attributes_revision_no: Option<AttributeRevisionNo>,
}

impl UpdateAttributesOptions {
    /// Creates an empty attribute update for this actor.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            set: BTreeMap::new(),
            remove: Vec::new(),
            commit: CommitOptions::new(actor),
            expected_inode_id: None,
            expected_attributes_revision_no: None,
        }
    }
}

/// Options for writing a file path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PutFileOptions {
    /// Create-only or replace-existing behavior.
    pub behavior: DestinationBehavior,
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
    /// The inode that the path must still reference when using `Replace` behavior.
    pub expected_inode_id: Option<InodeId>,
    /// The revision that must still be current when using `Replace` behavior with
    /// `expected_inode_id`.
    pub expected_revision_no: Option<RevisionNo>,
}

impl PutFileOptions {
    /// Creates options that refuse to replace an existing file.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            behavior: DestinationBehavior::NoReplace,
            commit: CommitOptions::new(actor),
            expected_inode_id: None,
            expected_revision_no: None,
        }
    }
}

/// Options for creating a directory.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CreateDirectoryOptions {
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
    /// Also create missing ancestor directories, like `put_file` does.
    pub parents: bool,
}

impl CreateDirectoryOptions {
    /// Creates options that do not create missing parent directories.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            commit: CommitOptions::new(actor),
            parents: false,
        }
    }
}

/// Options for deleting a path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DeleteOptions {
    /// Directory delete behavior.
    pub behavior: DeleteDirectoryBehavior,
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
    /// The inode that the path must still resolve to before deletion.
    pub expected_inode_id: Option<InodeId>,
}

impl DeleteOptions {
    /// Creates options for a non-recursive delete.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            behavior: DeleteDirectoryBehavior::NonRecursive,
            commit: CommitOptions::new(actor),
            expected_inode_id: None,
        }
    }
}

/// Options for moving a path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MoveOptions {
    /// Create-only or replace-existing behavior for the destination.
    pub behavior: DestinationBehavior,
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
    /// The inode that the destination must still reference when using `Replace` behavior.
    pub expected_destination_inode_id: Option<InodeId>,
    /// The revision that must still be current when using `Replace` behavior with
    /// `expected_destination_inode_id`.
    pub expected_destination_revision_no: Option<RevisionNo>,
}

impl MoveOptions {
    /// Creates options that refuse to replace the destination.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            behavior: DestinationBehavior::NoReplace,
            commit: CommitOptions::new(actor),
            expected_destination_inode_id: None,
            expected_destination_revision_no: None,
        }
    }
}

/// Options for copying a file path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CopyOptions {
    /// Create-only or replace-existing behavior for the destination.
    pub behavior: DestinationBehavior,
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
    /// The inode that the destination must still reference when using `Replace` behavior.
    pub expected_destination_inode_id: Option<InodeId>,
    /// The revision that must still be current when using `Replace` behavior with
    /// `expected_destination_inode_id`.
    pub expected_destination_revision_no: Option<RevisionNo>,
}

impl CopyOptions {
    /// Creates options that refuse to replace the destination.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            behavior: DestinationBehavior::NoReplace,
            commit: CommitOptions::new(actor),
            expected_destination_inode_id: None,
            expected_destination_revision_no: None,
        }
    }
}

/// Options for restoring a file revision by path.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RestoreRevisionOptions {
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
}

impl RestoreRevisionOptions {
    /// Creates restore options for this actor.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            commit: CommitOptions::new(actor),
        }
    }
}

/// Options for recovering a deleted file or subtree.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UndeleteOptions {
    /// Actor, commit ID, and message.
    pub commit: CommitOptions,
}

impl UndeleteOptions {
    /// Creates undelete options for this actor.
    pub fn new(actor: ActorRef) -> Self {
        Self {
            commit: CommitOptions::new(actor),
        }
    }
}

/// Options for starting a direct multipart upload.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct DirectMultipartUploadOptions {
    /// The byte length of every part except the last, or `None` for the server
    /// default; providers allow at most 10,000 parts.
    pub part_size_bytes: Option<u64>,
}
