//! Per-operation options and payloads shared by the embedded runtime and HTTP
//! client.

use crate::PinId;
use crate::{
    AccessGrants, AccessRevisionNo, AttributeKey, AttributeValue, AttributesRevisionNo, CommitId,
    CommitPrecondition, DeleteDirectoryBehavior, DestinationBehavior, InodeId, RevisionNo,
};
use std::collections::BTreeMap;

/// Whether a path or inode read includes the attribute projection.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub enum AttributeInclusion {
    /// Include the inode's attribute map and revision.
    Include,
    /// Omit the inode's attribute map and revision.
    #[default]
    Omit,
}

impl std::fmt::Display for AttributeInclusion {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(match self {
            Self::Include => "true",
            Self::Omit => "false",
        })
    }
}

/// Commit settings shared by every filesystem mutation.
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct CommitOptions {
    /// The optional idempotency key, generated by LoonFS when absent.
    pub commit_id: Option<CommitId>,
    /// The optional commit message that forms part of the commit identity.
    pub message: Option<String>,
    /// Ordered admission conditions evaluated before any operations.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub preconditions: Vec<CommitPrecondition>,
}

/// Options for stating one entry by path or by inode.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct StatOptions {
    /// Whether to include the inode's attribute map and revision, enabled by default.
    pub include_attributes: AttributeInclusion,
    /// Read the entry from this snapshot.
    pub snapshot_id: Option<PinId>,
}

impl Default for StatOptions {
    fn default() -> Self {
        Self {
            include_attributes: AttributeInclusion::Include,
            snapshot_id: None,
        }
    }
}

/// Options for listing a directory by path or by inode.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ListOptions {
    /// Whether to include each entry's attribute map and revision, disabled by default.
    pub include_attributes: AttributeInclusion,
    /// Read the directory from this snapshot.
    pub snapshot_id: Option<PinId>,
}

/// The attribute writes and removals one update applies.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct AttributeChanges {
    /// The attributes to write, replacing values for matching keys and leaving other
    /// keys unchanged.
    pub set: BTreeMap<AttributeKey, AttributeValue>,
    /// Keys to remove.
    pub remove: Vec<AttributeKey>,
}

/// Options for writing and removing an inode's attributes.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct UpdateAttributesOptions {
    /// Commit ID, message, and preconditions.
    pub commit: CommitOptions,
    /// The inode that the path must still resolve to before the update.
    pub expected_inode_id: Option<InodeId>,
    /// With an inode precondition, the attribute revision that must still be current.
    pub expected_attributes_revision_no: Option<AttributesRevisionNo>,
}

/// An inode's complete direct access: the state an access update writes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AccessState {
    /// Whether the directory stops inheritance from its ancestors.
    pub boundary: bool,
    /// The complete direct grants after the update.
    pub grants: AccessGrants,
}

/// Options for replacing an inode's access row.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct UpdateAccessOptions {
    /// Commit ID, message, and preconditions.
    pub commit: CommitOptions,
    /// The inode that the path must still resolve to before the update.
    pub expected_inode_id: Option<InodeId>,
    /// With an inode precondition, the access revision that must still be current.
    pub expected_access_revision_no: Option<AccessRevisionNo>,
}

/// Options for writing a file path.
#[derive(Debug, Clone, Default, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PutFileOptions {
    /// Create-only or replace-existing behavior.
    pub behavior: DestinationBehavior,
    /// Commit ID, message, and preconditions.
    pub commit: CommitOptions,
    /// The inode that the path must still reference when using `Replace` behavior.
    pub expected_inode_id: Option<InodeId>,
    /// The revision that must still be current when using `Replace` behavior with
    /// `expected_inode_id`.
    pub expected_revision_no: Option<RevisionNo>,
}

/// Options for creating a directory.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CreateDirectoryOptions {
    /// Commit ID, message, and preconditions.
    pub commit: CommitOptions,
    /// Also create missing ancestor directories, like `put_file` does.
    pub parents: bool,
}

/// Options for deleting a path.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DeleteOptions {
    /// Directory delete behavior.
    pub behavior: DeleteDirectoryBehavior,
    /// Commit ID, message, and preconditions.
    pub commit: CommitOptions,
    /// The inode that the path must still resolve to before deletion.
    pub expected_inode_id: Option<InodeId>,
}

/// Options for moving a path.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct MoveOptions {
    /// Create-only or replace-existing behavior for the destination.
    pub behavior: DestinationBehavior,
    /// Commit ID, message, and preconditions.
    pub commit: CommitOptions,
    /// The inode that the destination must still reference when using `Replace` behavior.
    pub expected_destination_inode_id: Option<InodeId>,
    /// The revision that must still be current when using `Replace` behavior with
    /// `expected_destination_inode_id`.
    pub expected_destination_revision_no: Option<RevisionNo>,
}

/// Options for copying a file path.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct CopyOptions {
    /// Create-only or replace-existing behavior for the destination.
    pub behavior: DestinationBehavior,
    /// Commit ID, message, and preconditions.
    pub commit: CommitOptions,
    /// The inode that the destination must still reference when using `Replace` behavior.
    pub expected_destination_inode_id: Option<InodeId>,
    /// The revision that must still be current when using `Replace` behavior with
    /// `expected_destination_inode_id`.
    pub expected_destination_revision_no: Option<RevisionNo>,
}

/// Options for starting a direct multipart upload.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct DirectMultipartUploadOptions {
    /// The byte length of every part except the last, or `None` for the server
    /// default; providers allow at most 10,000 parts.
    pub part_size_bytes: Option<u64>,
}

/// Selects the source state for a namespace fork.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct ForkNamespaceOptions {
    /// Fork from this live snapshot instead of the current head.
    pub snapshot_id: Option<crate::PinId>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn mutation_options_default_to_no_replace_no_preconditions_and_no_commit_settings() {
        let commit = CommitOptions {
            commit_id: None,
            message: None,
            preconditions: Vec::new(),
        };
        assert_eq!(CommitOptions::default(), commit);
        assert_eq!(
            PutFileOptions::default(),
            PutFileOptions {
                behavior: DestinationBehavior::NoReplace,
                commit: commit.clone(),
                expected_inode_id: None,
                expected_revision_no: None,
            }
        );
        assert_eq!(
            CreateDirectoryOptions::default(),
            CreateDirectoryOptions {
                commit: commit.clone(),
                parents: false,
            }
        );
        assert_eq!(
            DeleteOptions::default(),
            DeleteOptions {
                behavior: DeleteDirectoryBehavior::NonRecursive,
                commit: commit.clone(),
                expected_inode_id: None,
            }
        );
        assert_eq!(
            MoveOptions::default(),
            MoveOptions {
                behavior: DestinationBehavior::NoReplace,
                commit: commit.clone(),
                expected_destination_inode_id: None,
                expected_destination_revision_no: None,
            }
        );
        assert_eq!(
            CopyOptions::default(),
            CopyOptions {
                behavior: DestinationBehavior::NoReplace,
                commit: commit.clone(),
                expected_destination_inode_id: None,
                expected_destination_revision_no: None,
            }
        );
        assert_eq!(
            UpdateAttributesOptions::default(),
            UpdateAttributesOptions {
                commit: commit.clone(),
                expected_inode_id: None,
                expected_attributes_revision_no: None,
            }
        );
        assert_eq!(
            UpdateAccessOptions::default(),
            UpdateAccessOptions {
                commit,
                expected_inode_id: None,
                expected_access_revision_no: None,
            }
        );
        assert_eq!(
            ForkNamespaceOptions::default(),
            ForkNamespaceOptions { snapshot_id: None }
        );
    }
}
