[package]
name = "loon-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
loon-types = { path = "../loon-types" }
rusqlite.workspace = true
thiserror.workspace = true

[dev-dependencies]
loon-testkit = { path = "../loon-testkit" }
