[package]
name = "loon-client"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
serde.workspace = true
loon-types = { path = "../loon-types" }
loon-objectstore = { path = "../loon-objectstore" }
loon-sim = { path = "../loon-sim" }
rusqlite.workspace = true
thiserror.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
loon-model = { path = "../loon-model" }
loon-testkit = { path = "../loon-testkit" }
loon-server = { path = "../loon-server" }
loon-core = { path = "../loon-core" }
serde_yaml.workspace = true
