[package]
name = "loon-testkit"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_yaml.workspace = true

[dev-dependencies]
loon-core = { path = "../loon-core" }
loon-model = { path = "../loon-model" }
loon-objectstore = { path = "../loon-objectstore" }
loon-types = { path = "../loon-types" }
serde_json.workspace = true
