[package]
name = "loon-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "loon"
path = "src/main.rs"

[dependencies]
clap.workspace = true
http.workspace = true
loon-api = { path = "../loon-api" }
loon-client = { path = "../loon-client" }
loon-server = { path = "../loon-server" }
serde.workspace = true
serde_json.workspace = true
sysinfo.workspace = true
toml.workspace = true

[dev-dependencies]
insta = { version = "1.39", features = ["json"] }
tempfile.workspace = true
ureq.workspace = true
